### ISSUE TITLE
spp displacement and expansion

### ISSUE THREAD

**Issue by cmahony** [whmacken/CCISS_JournalPaper#1]
@whmacken, 
Over the break I did some thinking/coding on how to represent risk and opportunity by species in an efficient way. I came up with an approach that I want your feedback on. 

for background here is the change in suitability across the province for the six focal species, plotted against change in MAT. the points are only shown for the C4 edatope. a 1-stdev prediction interval is shown for the other edatopes. 
![CCISS SuitChangeVsTempChange EdatopeBySpp](https://user-images.githubusercontent.com/17104005/55352053-d2bc3500-5474-11e9-8d22-f0d5e9d1f555.png)

there are two things going on to produce these trends: (1) the suitability is changing (generally declining) in locations where the species was historically suitable, and (2) the species may be becoming suitable in locations where it historically was not. These dynamics can be called **displacement** and **expansion**. displacement is a measure of _risk_; expansion is a measure of _opportunity_. 

here is the displacement for the focal species. negative displacement indicates the mean suitability is increasing within historically suitable areas.  
![CCISS DisplacementVsTempChange EdatopeBySpp](https://user-images.githubusercontent.com/17104005/55352483-c97f9800-5475-11e9-860d-8227c12c947e.png)

here is the expansion. 
![CCISS ExpansionVsTempChange EdatopeBySpp](https://user-images.githubusercontent.com/17104005/55352728-5e829100-5476-11e9-8588-6dd400bae66f.png)

these two indices allow us to put all species on one plot, with displacement (risk) on the x axis and expansion (opportunity) on the y axis. Pa is the biggest loser: almost fully displaced with no expansion. Ra is also in this category. as might be expected, Yc and Hm are high-displacement/low expansion species. I did not expect the top-right half of the plot to be empty; this likely is because species with small ranges/niches are likely to expand less and be displaced more. 
![CCISS ExpansionAbsVsDisplacement 2055 rcp45 C4](https://user-images.githubusercontent.com/17104005/55352852-af928500-5476-11e9-9c09-3b98b96b5ff3.png)

here are the same plots for the other two edatopes. 
![CCISS ExpansionAbsVsDisplacement 2055 rcp45 B2](https://user-images.githubusercontent.com/17104005/55353708-e073b980-5478-11e9-8a0e-b765aea2d760.png)

![CCISS ExpansionAbsVsDisplacement 2055 rcp45 D6](https://user-images.githubusercontent.com/17104005/55353721-e5d10400-5478-11e9-8a45-1a66d074569e.png)

**Comment by cmahony** [comment]
@whmacken made this comment by email: 
"I like the direction you have taken here. I actually think the independent graphs are a little clearer in the message at this point. And what are the points on those graphs exactly?
I wonder if the Y-axis in the combined expansion/displacement should actually be % of historic range rather than km2 as this would scale for more vs less common species and might lead to a filling of the upper right quadrat. In a graphic like that a 1:1 trend line could be put in place and species that fall above line would be generally “improving” provincially and those below the line “declining”."

**Comment by cmahony** [comment]
@whmacken 
to clarify, the dot for each species is the mean expansion or displacement for that species across the 15 model projections in the ensemble for the specified time period and scenario.  the ellipse is the 50th-percentile of probability for the 15 model projections. 

Here is the plot as a % of historic range, with the 1:1 line that you suggested. overall, i think this is a more interpretable plot, especially as it facilitates the 1:1 line, which is a big improvement. it gives a different type of information than the absolute expansion in area, since it downplays opportunities in species that already have large ranges. spp with very small ranges can be over-inflated in the relative plot (e.g. Bg). 
![CCISS ExpansionVsDisplacement 2055 rcp45 C4](https://user-images.githubusercontent.com/17104005/55362646-70bcf900-548f-11e9-8eec-19c8d1547583.png)

one way to put these small-denominator (small historic range) species under control is to use a log-transformation of the y axis. however, this makes the plot less intuitive for most viewers, so i don't prefer it. 
![CCISS ExpansionLogVsDisplacement 2055 rcp45 C4](https://user-images.githubusercontent.com/17104005/55362896-44ee4300-5490-11e9-8908-e2599541bb95.png)

here are the other two edatopes for the linear relative plot. 
![CCISS ExpansionVsDisplacement 2055 rcp45 B2](https://user-images.githubusercontent.com/17104005/55362968-6f400080-5490-11e9-8325-5a845a456f8f.png)
![CCISS ExpansionVsDisplacement 2055 rcp45 D6](https://user-images.githubusercontent.com/17104005/55362978-749d4b00-5490-11e9-9a70-4921d9c01381.png)

**Comment by whmacken** [comment]
Are there really no species that have contracting ranges (ie. negative exansion)?  Or is 100% expansion actually = the original extent?

**Comment by whmacken** [comment]
I prefer the Log scale plot as it does make it easier to see the above/below line relationship, i think. And curved lines are cooler.

**Comment by cmahony** [comment]
yrsh, on second thought, I agree. Just needs a bit more explaining.

**Comment by cmahony** [comment]
Something wrong with github. I don't see this comment on the issue.
Anyway, the y axis is new suitability in cells with no historical suitability. So the minimum is zero, and negative values are not possible.


Colin Mahony PhD, RPF
Postdoctoral Researcher
UBC Department of Forest and Conservation Sciences
778-288-4008

**Comment by whmacken** [comment]
I had removed that comment as I had already figured it out.

**Comment by cmahony** [comment]
@whmacken, 
I've put together a manuscript figure that integrates these plots. a few notes: 
1. I've changed the "displacement" metric to "persistence". it works better conceptually. suitable area = persistence + expansion. 
2, all of these metrics multiply the area of each cell by the suitability (1=1, 2=0.75, 3=0.5, 4=0). so it is possible for persistence to be >1, but it almost never is (At is the only exception). 
3. i used Sx to illustrate the concepts. this lines up with the manuscript figure that provides suitability maps of spruce for each edatope. 

![CCISS manu ExpansionVsPersistence 2055 rcp45](https://user-images.githubusercontent.com/17104005/55429364-2a73a280-5540-11e9-9a1e-ac1f4f31962f.png)
