### ISSUE TITLE
Manu Figure: Persistence & expansion

### ISSUE THREAD

**Issue by cmahony** [whmacken/CCISS_JournalPaper#3]
Here is a manuscript figure for the concepts of expansion and persistence. comments are welcome. 

![CCISS manu ExpansionVsPersistence 2055 rcp45](https://user-images.githubusercontent.com/17104005/55656627-88a4bd80-57ac-11e9-8e21-030231048141.png)

**Comment by whmacken** [comment]
I think these are excellent. The labels on the dotted line need to be reworded. Growing range = Increasing area of suitability vs Declining area of suitability

**Comment by cmahony** [comment]
update the terminology and removed non-forested BGC units. 

![CCISS manu ExpansionVsPersistence THLB 2055 rcp45](https://user-images.githubusercontent.com/17104005/57792216-519ec180-76f3-11e9-8fee-2b37a8727a61.png)
