### ISSUE TITLE
Manu figure: BGC projections

### ISSUE THREAD

**Issue by cmahony** [whmacken/CCISS_JournalPaper#4]
@whmacken, 
here is a manuscript figure for the BGC projections. comments welcome. 

some notes: 
- maps for other time periods/rcp in supp info. 
- the boxplots show the range of temperature change across the ensemble for that time period and rcp. 
- panel D color codes exotic units by the BGC zone that they occupy in the 2050s. the whole unit is mapped. i wanted a map that shows where the exotic units are located. the other way to convey this type of information is to train the RF model on the future climates and predict to the reference period; that then shows the exotic locations with historical climates similar to BC's future climates. However, i think the way i've mapped exotic units here is more intuitive for this figure. 

![CCISS manu BGCprojections](https://user-images.githubusercontent.com/17104005/55657028-ceae5100-57ad-11e9-80f1-0d6439a1f880.png)

**Comment by whmacken** [comment]
These are good and have already been commented on
