### ISSUE TITLE
Add in analysis of suitability change of current existing climate change (61-90 v latest)

### ISSUE THREAD

**Issue by whmacken** [whmacken/CCISS_JournalPaper#9]

**Comment by whmacken** [comment]
Now that the post 2000 years are correct in ClimateBC, I had intended to analyse where there have already been changes in suitability (between the normal period and the last 15yrs (?)). This might be a required piece of the CCISS paper.

**Comment by whmacken** [comment]
We could also produce maps of suitability change between the reference period and the modern period - i.e. places most likely to achieve off-site species establishment success

**Comment by cmahony** [comment]
As discussed, this figure will go in the supp info. comments welcome.

![CCISS manu Suitability 4panel Pl Fd Cw Sx C4 2009](https://user-images.githubusercontent.com/17104005/57792070-07b5db80-76f3-11e9-901e-cd94121ae60a.png)
